# generated by datamodel-codegen:
#   filename:  https://www.thebluealliance.com/swagger/api_v3.json
#   timestamp: 2026-01-15T11:45:47+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Iterator

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class APIStatusAppVersion(BaseModel):
    min_app_version: int = Field(
        ...,
        description='Internal use - Minimum application version required to correctly connect and process data.',
    )
    latest_app_version: int = Field(
        ..., description='Internal use - Latest application version available.'
    )


class AutoChargeStationRobot2023(Enum):
    Docked = 'Docked'
    None_ = 'None'


class AutoLineRobot2024(Enum):
    No = 'No'
    Yes = 'Yes'


class AutoRobot2018(Enum):
    None_ = 'None'
    AutoRun = 'AutoRun'


class AwardRecipient(BaseModel):
    team_key: str | None = Field(
        ...,
        description='The TBA team key for the team that was given the award. May be null.',
    )
    awardee: str | None = Field(
        ..., description='The name of the individual given the award. May be null.'
    )


class Bay2019(Enum):
    None_ = 'None'
    Panel = 'Panel'
    PanelAndCargo = 'PanelAndCargo'


class BridgeState2023(Enum):
    Level = 'Level'
    NotLevel = 'NotLevel'


class CompLevel(Enum):
    qm = 'qm'
    ef = 'ef'
    qf = 'qf'
    sf = 'sf'
    f = 'f'


class District(BaseModel):
    abbreviation: str = Field(..., description='The short identifier for the district.')
    display_name: str = Field(..., description='The long name for the district.')
    key: str = Field(..., description='Key for this district, e.g. `2016ne`.')
    year: int = Field(..., description='Year this district participated.')


class DistrictInsightRegionData(BaseModel):
    yearly_active_team_count: dict[str, int] = Field(
        ..., description='Map of year to number of active teams'
    )
    yearly_event_count: dict[str, int] = Field(
        ..., description='Map of year to number of events'
    )
    yearly_gained_teams: dict[str, list[str]] = Field(
        ..., description='Map of year to list of team keys gained'
    )
    yearly_lost_teams: dict[str, list[str]] = Field(
        ..., description='Map of year to list of team keys lost'
    )


class DistrictAdvancement(BaseModel):
    dcmp: bool = Field(
        ...,
        description='Whether or not the team qualified for their District Championship',
    )
    cmp: bool = Field(
        ..., description='Whether or not the team qualified for the FIRST Championship'
    )


class DistrictData(BaseModel):
    region_data: dict[str, DistrictInsightRegionData] | None
    district_wide_data: DistrictInsightRegionData | None


class EventPoint(BaseModel):
    district_cmp: bool = Field(
        ..., description='`true` if this event is a District Championship event.'
    )
    total: int = Field(..., description='Total points awarded at this event.')
    alliance_points: int = Field(
        ..., description='Points awarded for alliance selection.'
    )
    elim_points: int = Field(
        ..., description='Points awarded for elimination match performance.'
    )
    award_points: int = Field(..., description='Points awarded for event awards.')
    event_key: str = Field(..., description='TBA Event key for this event.')
    qual_points: int = Field(
        ..., description='Points awarded for qualification match performance.'
    )


class DistrictRanking(BaseModel):
    team_key: str = Field(..., description='TBA team key for the team.')
    rank: int = Field(..., description='Numerical rank of the team, 1 being top rank.')
    rookie_bonus: int = Field(
        ..., description='Any points added to a team as a result of the rookie bonus.'
    )
    point_total: int = Field(..., description='Total district points for the team.')
    event_points: list[EventPoint] = Field(
        ...,
        description='List of events that contributed to the point total for the team.',
    )
    adjustments: int | None = Field(
        None, description='Any points adjustments applied to the team.'
    )
    other_bonus: int | None = Field(
        None, description='Any other bonus points awarded to the team.'
    )


class DoubleElimRound(Enum):
    Finals = 'Finals'
    Round_1 = 'Round 1'
    Round_2 = 'Round 2'
    Round_3 = 'Round 3'
    Round_4 = 'Round 4'
    Round_5 = 'Round 5'


class Backup(BaseModel):
    in_: str = Field(
        ..., alias='in', description='Team key that was called in as the backup.'
    )
    out: str = Field(..., description='Team key that was replaced by the backup team.')


class Record(BaseModel):
    losses: int = Field(..., description='Number of losses.')
    wins: int = Field(..., description='Number of wins.')
    ties: int = Field(..., description='Number of ties.')


class CurrentLevelRecord(BaseModel):
    losses: int = Field(..., description='Number of losses.')
    wins: int = Field(..., description='Number of wins.')
    ties: int = Field(..., description='Number of ties.')


class Status1(Enum):
    eliminated = 'eliminated'
    playing = 'playing'
    won = 'won'


class Status(BaseModel):
    playoff_average: float | None = Field(
        None,
        description='Average match score during playoffs. Year specific. May be null.',
    )
    playoff_type: float | None = Field(..., description='Playoff type, may be null.')
    level: CompLevel = Field(..., description='Match level, qm/ef/qf/sf/f.')
    record: Record | None = Field(
        ..., description='W-L-T record for the alliance, may be null.'
    )
    current_level_record: CurrentLevelRecord | None = Field(
        ...,
        description='W-L-T record for the alliance at the current level, may be null.',
    )
    status: Status1 = Field(..., description='Status of the alliance.')
    advanced_to_round_robin_finals: bool | None = Field(
        None, description='Whether the alliance advanced to round robin finals.'
    )
    double_elim_round: DoubleElimRound | None = None
    round_robin_rank: int | None = Field(None, description='Rank in round robin play.')


class EliminationAlliance(BaseModel):
    name: str | None = Field(None, description='Alliance name.')
    backup: Backup | None = Field(
        None, description='Backup team called in, may be null.'
    )
    declines: list[str] = Field(
        ..., description='List of teams that declined the alliance.'
    )
    picks: list[str] = Field(
        ...,
        description='List of team keys picked for the alliance. First pick is captain.',
    )
    status: Status | None = None


class EndGameChargeStationRobot2023(Enum):
    Docked = 'Docked'
    None_ = 'None'
    Park = 'Park'
    Parked = 'Parked'


class EndGameRobot2024(Enum):
    CenterStage = 'CenterStage'
    None_ = 'None'
    Parked = 'Parked'
    StageLeft = 'StageLeft'
    StageRight = 'StageRight'


class EndGameRobot2025(Enum):
    DeepCage = 'DeepCage'
    None_ = 'None'
    Parked = 'Parked'
    ShallowCage = 'ShallowCage'


class EndgameRobot2018(Enum):
    Climbing = 'Climbing'
    Levitate = 'Levitate'
    None_ = 'None'
    Parking = 'Parking'
    Unknown = 'Unknown'


class EndgameRobot2019(Enum):
    HabLevel1 = 'HabLevel1'
    HabLevel2 = 'HabLevel2'
    HabLevel3 = 'HabLevel3'
    None_ = 'None'
    Unknown = 'Unknown'


class EndgameRobot2020(Enum):
    Hang = 'Hang'
    None_ = 'None'
    Park = 'Park'


class EndgameRobot2022(Enum):
    High = 'High'
    Low = 'Low'
    Mid = 'Mid'
    None_ = 'None'
    Traversal = 'Traversal'


class EndgameRungIsLevel2020(Enum):
    IsLevel = 'IsLevel'
    NotLevel = 'NotLevel'


class EventCOPRs(RootModel[dict[str, dict[str, float]]]):
    root: dict[str, dict[str, float]] = Field(
        ...,
        description='A key-value pair with team key (eg `frc254`) as key and CCWM as value.',
    )


class Points(BaseModel):
    total: int = Field(..., description='Total points awarded at this event.')
    alliance_points: int = Field(
        ..., description='Points awarded for alliance selection'
    )
    elim_points: int = Field(
        ..., description='Points awarded for elimination match performance.'
    )
    award_points: int = Field(..., description='Points awarded for event awards.')
    qual_points: int = Field(
        ..., description='Points awarded for qualification match performance.'
    )


class Tiebreakers(BaseModel):
    highest_qual_scores: list[int] | None = None
    qual_wins: int | None = None


class EventDistrictPoints(BaseModel):
    points: dict[str, Points] = Field(
        ...,
        description='Points gained for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the points as its value.',
    )
    tiebreakers: dict[str, Tiebreakers] | None = Field(
        None,
        description='Tiebreaker values for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the tiebreaker elements as its value.',
    )


class EventInsights(BaseModel):
    qual: dict[str, Any] | None = Field(
        None, description='Inights for the qualification round of an event'
    )
    playoff: dict[str, Any] | None = Field(
        None, description='Insights for the playoff round of an event'
    )


class EventInsights2016(BaseModel):
    LowBar: list[float] = Field(
        ...,
        description='For the Low Bar - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    A_ChevalDeFrise: list[float] = Field(
        ...,
        description='For the Cheval De Frise - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    A_Portcullis: list[float] = Field(
        ...,
        description='For the Portcullis - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    B_Ramparts: list[float] = Field(
        ...,
        description='For the Ramparts - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    B_Moat: list[float] = Field(
        ...,
        description='For the Moat - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    C_SallyPort: list[float] = Field(
        ...,
        description='For the Sally Port - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    C_Drawbridge: list[float] = Field(
        ...,
        description='For the Drawbridge - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    D_RoughTerrain: list[float] = Field(
        ...,
        description='For the Rough Terrain - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    D_RockWall: list[float] = Field(
        ...,
        description='For the Rock Wall - An array with three values, number of times damaged, number of opportunities to damage, and percentage.',
    )
    average_high_goals: float = Field(
        ..., description='Average number of high goals scored.'
    )
    average_low_goals: float = Field(
        ..., description='Average number of low goals scored.'
    )
    breaches: list[float] = Field(
        ...,
        description='An array with three values, number of times breached, number of opportunities to breach, and percentage.',
    )
    scales: list[float] = Field(
        ...,
        description='An array with three values, number of times scaled, number of opportunities to scale, and percentage.',
    )
    challenges: list[float] = Field(
        ...,
        description='An array with three values, number of times challenged, number of opportunities to challenge, and percentage.',
    )
    captures: list[float] = Field(
        ...,
        description='An array with three values, number of times captured, number of opportunities to capture, and percentage.',
    )
    average_win_score: float = Field(..., description='Average winning score.')
    average_win_margin: float = Field(..., description='Average margin of victory.')
    average_score: float = Field(..., description='Average total score.')
    average_auto_score: float = Field(..., description='Average autonomous score.')
    average_crossing_score: float = Field(..., description='Average crossing score.')
    average_boulder_score: float = Field(..., description='Average boulder score.')
    average_tower_score: float = Field(..., description='Average tower score.')
    average_foul_score: float = Field(..., description='Average foul score.')
    high_score: list[str] = Field(
        ...,
        description='An array with three values, high score, match key from the match with the high score, and the name of the match.',
    )


class EventInsights2017(BaseModel):
    average_foul_score: float = Field(..., description='Average foul score.')
    average_fuel_points: float = Field(..., description='Average fuel points scored.')
    average_fuel_points_auto: float = Field(
        ..., description='Average fuel points scored during auto.'
    )
    average_fuel_points_teleop: float = Field(
        ..., description='Average fuel points scored during teleop.'
    )
    average_high_goals: float = Field(
        ..., description='Average points scored in the high goal.'
    )
    average_high_goals_auto: float = Field(
        ..., description='Average points scored in the high goal during auto.'
    )
    average_high_goals_teleop: float = Field(
        ..., description='Average points scored in the high goal during teleop.'
    )
    average_low_goals: float = Field(
        ..., description='Average points scored in the low goal.'
    )
    average_low_goals_auto: float = Field(
        ..., description='Average points scored in the low goal during auto.'
    )
    average_low_goals_teleop: float = Field(
        ..., description='Average points scored in the low goal during teleop.'
    )
    average_mobility_points_auto: float = Field(
        ..., description='Average mobility points scored during auto.'
    )
    average_points_auto: float = Field(
        ..., description='Average points scored during auto.'
    )
    average_points_teleop: float = Field(
        ..., description='Average points scored during teleop.'
    )
    average_rotor_points: float = Field(..., description='Average rotor points scored.')
    average_rotor_points_auto: float = Field(
        ..., description='Average rotor points scored during auto.'
    )
    average_rotor_points_teleop: float = Field(
        ..., description='Average rotor points scored during teleop.'
    )
    average_score: float = Field(..., description='Average score.')
    average_takeoff_points_teleop: float = Field(
        ..., description='Average takeoff points scored during teleop.'
    )
    average_win_margin: float = Field(..., description='Average margin of victory.')
    average_win_score: float = Field(..., description='Average winning score.')
    high_kpa: list[str] = Field(
        ...,
        description='An array with three values, kPa scored, match key from the match with the high kPa, and the name of the match',
    )
    high_score: list[str] = Field(
        ...,
        description='An array with three values, high score, match key from the match with the high score, and the name of the match',
    )
    kpa_achieved: list[float] = Field(
        ...,
        description='An array with three values, number of times kPa bonus achieved, number of opportunities to bonus, and percentage.',
    )
    mobility_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times mobility bonus achieved, number of opportunities to bonus, and percentage.',
    )
    rotor_1_engaged: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 1 engaged, number of opportunities to engage, and percentage.',
    )
    rotor_1_engaged_auto: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 1 engaged in auto, number of opportunities to engage in auto, and percentage.',
    )
    rotor_2_engaged: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 2 engaged, number of opportunities to engage, and percentage.',
    )
    rotor_2_engaged_auto: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 2 engaged in auto, number of opportunities to engage in auto, and percentage.',
    )
    rotor_3_engaged: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 3 engaged, number of opportunities to engage, and percentage.',
    )
    rotor_4_engaged: list[float] = Field(
        ...,
        description='An array with three values, number of times rotor 4 engaged, number of opportunities to engage, and percentage.',
    )
    takeoff_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times takeoff was counted, number of opportunities to takeoff, and percentage.',
    )
    unicorn_matches: list[float] = Field(
        ...,
        description='An array with three values, number of times a unicorn match (Win + kPa & Rotor Bonuses) occured, number of opportunities to have a unicorn match, and percentage.',
    )


class EventInsights2018(BaseModel):
    auto_quest_achieved: list[float] = Field(
        ...,
        description='An array with three values, number of times auto quest was completed, number of opportunities to complete the auto quest, and percentage.',
    )
    average_boost_played: float = Field(
        ..., description='Average number of boost power up scored (out of 3).'
    )
    average_endgame_points: float = Field(..., description='Average endgame points.')
    average_force_played: float = Field(
        ..., description='Average number of force power up scored (out of 3).'
    )
    average_foul_score: float = Field(..., description='Average foul score.')
    average_points_auto: float = Field(
        ..., description='Average points scored during auto.'
    )
    average_points_teleop: float = Field(
        ..., description='Average points scored during teleop.'
    )
    average_run_points_auto: float = Field(
        ..., description='Average mobility points scored during auto.'
    )
    average_scale_ownership_points: float = Field(
        ..., description='Average scale ownership points scored.'
    )
    average_scale_ownership_points_auto: float = Field(
        ..., description='Average scale ownership points scored during auto.'
    )
    average_scale_ownership_points_teleop: float = Field(
        ..., description='Average scale ownership points scored during teleop.'
    )
    average_score: float = Field(..., description='Average score.')
    average_switch_ownership_points: float = Field(
        ..., description='Average switch ownership points scored.'
    )
    average_switch_ownership_points_auto: float = Field(
        ..., description='Average switch ownership points scored during auto.'
    )
    average_switch_ownership_points_teleop: float = Field(
        ..., description='Average switch ownership points scored during teleop.'
    )
    average_vault_points: float = Field(..., description='Average value points scored.')
    average_win_margin: float = Field(..., description='Average margin of victory.')
    average_win_score: float = Field(..., description='Average winning score.')
    boost_played_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times a boost power up was played, number of opportunities to play a boost power up, and percentage.',
    )
    climb_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times a climb occurred, number of opportunities to climb, and percentage.',
    )
    face_the_boss_achieved: list[float] = Field(
        ...,
        description='An array with three values, number of times an alliance faced the boss, number of opportunities to face the boss, and percentage.',
    )
    force_played_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times a force power up was played, number of opportunities to play a force power up, and percentage.',
    )
    high_score: list[str] = Field(
        ...,
        description='An array with three values, high score, match key from the match with the high score, and the name of the match',
    )
    levitate_played_counts: list[float] = Field(
        ...,
        description='An array with three values, number of times a levitate power up was played, number of opportunities to play a levitate power up, and percentage.',
    )
    run_counts_auto: list[float] = Field(
        ...,
        description='An array with three values, number of times a team scored mobility points in auto, number of opportunities to score mobility points in auto, and percentage.',
    )
    scale_neutral_percentage: float = Field(
        ..., description='Average scale neutral percentage.'
    )
    scale_neutral_percentage_auto: float = Field(
        ..., description='Average scale neutral percentage during auto.'
    )
    scale_neutral_percentage_teleop: float = Field(
        ..., description='Average scale neutral percentage during teleop.'
    )
    switch_owned_counts_auto: list[float] = Field(
        ...,
        description='An array with three values, number of times a switch was owned during auto, number of opportunities to own a switch during auto, and percentage.',
    )
    unicorn_matches: list[float] = Field(
        ...,
        description='An array with three values, number of times a unicorn match (Win + Auto Quest + Face the Boss) occurred, number of opportunities to have a unicorn match, and percentage.',
    )
    winning_opp_switch_denial_percentage_teleop: float = Field(
        ...,
        description='Average opposing switch denail percentage for the winning alliance during teleop.',
    )
    winning_own_switch_ownership_percentage: float = Field(
        ...,
        description='Average own switch ownership percentage for the winning alliance.',
    )
    winning_own_switch_ownership_percentage_auto: float = Field(
        ...,
        description='Average own switch ownership percentage for the winning alliance during auto.',
    )
    winning_own_switch_ownership_percentage_teleop: float = Field(
        ...,
        description='Average own switch ownership percentage for the winning alliance during teleop.',
    )
    winning_scale_ownership_percentage: float = Field(
        ..., description='Average scale ownership percentage for the winning alliance.'
    )
    winning_scale_ownership_percentage_auto: float = Field(
        ...,
        description='Average scale ownership percentage for the winning alliance during auto.',
    )
    winning_scale_ownership_percentage_teleop: float = Field(
        ...,
        description='Average scale ownership percentage for the winning alliance during teleop.',
    )


class EventOPRs(BaseModel):
    oprs: dict[str, float] | None = Field(
        None,
        description='A key-value pair with team key (eg `frc254`) as key and OPR as value.',
    )
    dprs: dict[str, float] | None = Field(
        None,
        description='A key-value pair with team key (eg `frc254`) as key and DPR as value.',
    )
    ccwms: dict[str, float] | None = Field(
        None,
        description='A key-value pair with team key (eg `frc254`) as key and CCWM as value.',
    )


class EventPredictions(BaseModel):
    pass


class Ranking(BaseModel):
    matches_played: int = Field(
        ..., description='Number of matches played by this team.'
    )
    qual_average: int | None = Field(
        ...,
        description='The average match score during qualifications. Year specific. May be null if not relevant for a given year.',
    )
    extra_stats: list[float] = Field(
        ...,
        description="Additional special data on the team's performance calculated by TBA.",
    )
    sort_orders: list[float] = Field(
        ...,
        description='Additional year-specific information. See parent `sort_order_info` for details.',
    )
    record: Record | None
    rank: int = Field(
        ..., description="The team's rank at the event as provided by FIRST."
    )
    dq: int = Field(..., description='Number of times disqualified.')
    team_key: str = Field(..., description='The team with this rank.')


class ExtraStatsInfoItem(BaseModel):
    precision: float = Field(
        ...,
        description='Integer expressing the number of digits of precision in the number provided in `sort_orders`.',
    )
    name: str = Field(
        ..., description='Name of the field used in the `extra_stats` array.'
    )


class SortOrderInfoItem(BaseModel):
    precision: int = Field(
        ...,
        description='Integer expressing the number of digits of precision in the number provided in `sort_orders`.',
    )
    name: str = Field(
        ..., description='Name of the field used in the `sort_order` array.'
    )


class EventRanking(BaseModel):
    rankings: list[Ranking] = Field(..., description='List of rankings at the event.')
    extra_stats_info: list[ExtraStatsInfoItem] = Field(
        ...,
        description='List of special TBA-generated values provided in the `extra_stats` array for each item.',
    )
    sort_order_info: list[SortOrderInfoItem] | None = Field(
        ...,
        description='List of year-specific values provided in the `sort_orders` array for each team.',
    )


class EventSimple(BaseModel):
    key: str = Field(
        ...,
        description='TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.',
    )
    name: str = Field(
        ...,
        description='Official name of event on record either provided by FIRST or organizers of offseason event.',
    )
    event_code: str = Field(..., description='Event short code, as provided by FIRST.')
    event_type: int = Field(
        ...,
        description='Event Type, as defined here: https://github.com/the-blue-alliance/the-blue-alliance/blob/main/src/backend/common/consts/event_type.py#L8',
    )
    district: District | None
    city: str | None = Field(
        ..., description='City, town, village, etc. the event is located in.'
    )
    state_prov: str | None = Field(
        ..., description='State or Province the event is located in.'
    )
    country: str | None = Field(..., description='Country the event is located in.')
    start_date: date = Field(
        ..., description='Event start date in `yyyy-mm-dd` format.'
    )
    end_date: date = Field(..., description='Event end date in `yyyy-mm-dd` format.')
    year: int = Field(..., description='Year the event data is for.')


class HabLine2019(Enum):
    CrossedHabLineInSandstorm = 'CrossedHabLineInSandstorm'
    CrossedHabLineInTeleop = 'CrossedHabLineInTeleop'
    None_ = 'None'
    Unknown = 'Unknown'


class InitLineRobot2020(Enum):
    Exited = 'Exited'
    None_ = 'None'


class Ranking1(BaseModel):
    value: float = Field(
        ...,
        description='Value of the insight that the corresponding team/event/matches have, e.g. number of blue banners, or number of matches played.',
    )
    keys: list[str] = Field(
        ..., description='Team/Event/Match keys that have the corresponding value.'
    )


class KeyType(Enum):
    team = 'team'
    event = 'event'
    match = 'match'


class Data(BaseModel):
    rankings: list[Ranking1]
    key_type: KeyType = Field(
        ...,
        description="What type of key is used in the rankings; either 'team', 'event', or 'match'.",
    )


class LeaderboardInsight(BaseModel):
    data: Data
    name: str = Field(..., description='Name of the insight.')
    year: int = Field(
        ...,
        description='Year the insight was measured in (year=0 for overall insights).',
    )


class WinningAlliance(Enum):
    red = 'red'
    blue = 'blue'
    field_ = ''


class Video(BaseModel):
    type: str = Field(..., description="Can be one of 'youtube' or 'tba'")
    key: str = Field(..., description='Unique key representing this video')


class Coopertition(Enum):
    None_ = 'None'
    Unknown = 'Unknown'
    Stack = 'Stack'


class MatchScoreBreakdown2015Alliance(BaseModel):
    auto: str | None = None
    auto_points: int | None = None
    teleop_points: int | None = None
    container_points: int | None = None
    tote_points: int | None = None
    litter_points: int | None = None
    foul: str | None = None
    foul_points: int | None = None
    adjust_points: int | None = None
    total_points: int | None = None
    foul_count: int | None = None
    tote_count_far: int | None = None
    tote_count_near: int | None = None
    tote_set: bool | None = None
    tote_stack: bool | None = None
    container_count_level1: int | None = None
    container_count_level2: int | None = None
    container_count_level3: int | None = None
    container_count_level4: int | None = None
    container_count_level5: int | None = None
    container_count_level6: int | None = None
    container_set: bool | None = None
    litter_count_container: int | None = None
    litter_count_landfill: int | None = None
    litter_count_unprocessed: int | None = None
    robot_set: bool | None = None


class TbaGameData(Enum):
    field_ = ''
    LLL = 'LLL'
    LRL = 'LRL'
    RLR = 'RLR'
    RRR = 'RRR'


class MatchScoreBreakdown2018Alliance(BaseModel):
    adjustPoints: int | None = None
    autoOwnershipPoints: int
    autoPoints: int
    autoQuestRankingPoint: bool | None = None
    autoRobot1: AutoRobot2018 | None = None
    autoRobot2: AutoRobot2018 | None = None
    autoRobot3: AutoRobot2018 | None = None
    autoRunPoints: int
    autoScaleOwnershipSec: int
    autoSwitchAtZero: bool | None = None
    autoSwitchOwnershipSec: int
    endgamePoints: int
    endgameRobot1: EndgameRobot2018 | None = None
    endgameRobot2: EndgameRobot2018 | None = None
    endgameRobot3: EndgameRobot2018 | None = None
    faceTheBossRankingPoint: bool
    foulCount: int | None = None
    foulPoints: int
    rp: int
    techFoulCount: int | None = None
    teleopOwnershipPoints: int
    teleopPoints: int
    teleopScaleBoostSec: int
    teleopScaleForceSec: int | None = None
    teleopScaleOwnershipSec: int
    teleopSwitchBoostSec: int
    teleopSwitchForceSec: int | None = None
    teleopSwitchOwnershipSec: int
    totalPoints: int
    vaultBoostPlayed: int
    vaultBoostTotal: int
    vaultForcePlayed: int
    vaultForceTotal: int
    vaultLevitatePlayed: int
    vaultLevitateTotal: int
    vaultPoints: int
    tba_gameData: TbaGameData | None = Field(
        None,
        description="Unofficial TBA-computed value of the FMS provided GameData given to the alliance teams at the start of the match. 3 Character String containing `L` and `R` only. The first character represents the near switch, the 2nd the scale, and the 3rd the far, opposing, switch from the alliance's perspective. An `L` in a position indicates the platform on the left will be lit for the alliance while an `R` will indicate the right platform will be lit for the alliance. See also [WPI Screen Steps](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details).",
    )


class BEnum(Enum):
    None_ = 'None'
    Cone = 'Cone'
    Cube = 'Cube'


class MEnum(Enum):
    None_ = 'None'
    Cone = 'Cone'
    Cube = 'Cube'


class TEnum(Enum):
    None_ = 'None'
    Cone = 'Cone'
    Cube = 'Cube'


class AutoCommunity(BaseModel):
    B: list[BEnum]
    M: list[MEnum]
    T: list[TEnum]


class Node(Enum):
    None_ = 'None'
    Cone = 'Cone'
    Cube = 'Cube'


class Row(Enum):
    Bottom = 'Bottom'
    Mid = 'Mid'
    Top = 'Top'


class Link(BaseModel):
    nodes: list[Node]
    row: Row


class TeleopCommunity(BaseModel):
    B: list[BEnum]
    M: list[MEnum]
    T: list[TEnum]


class MatchScoreBreakdown2024Alliance(BaseModel):
    adjustPoints: int | None = None
    autoAmpNoteCount: int | None = None
    autoAmpNotePoints: int | None = None
    autoLeavePoints: int | None = None
    autoLineRobot1: AutoLineRobot2024 | None = None
    autoLineRobot2: AutoLineRobot2024 | None = None
    autoLineRobot3: AutoLineRobot2024 | None = None
    autoPoints: int | None = None
    autoSpeakerNoteCount: int | None = None
    autoSpeakerNotePoints: int | None = None
    autoTotalNotePoints: int | None = None
    coopNotePlayed: bool | None = None
    coopertitionBonusAchieved: bool | None = None
    coopertitionCriteriaMet: bool | None = None
    endGameHarmonyPoints: int | None = None
    endGameNoteInTrapPoints: int | None = None
    endGameOnStagePoints: int | None = None
    endGameParkPoints: int | None = None
    endGameRobot1: EndGameRobot2024 | None = None
    endGameRobot2: EndGameRobot2024 | None = None
    endGameRobot3: EndGameRobot2024 | None = None
    endGameSpotLightBonusPoints: int | None = None
    endGameTotalStagePoints: int | None = None
    ensembleBonusAchieved: bool | None = None
    ensembleBonusOnStageRobotsThreshold: int | None = None
    ensembleBonusStagePointsThreshold: int | None = None
    foulCount: int | None = None
    foulPoints: int | None = None
    g206Penalty: bool | None = None
    g408Penalty: bool | None = None
    g424Penalty: bool | None = None
    melodyBonusAchieved: bool | None = None
    melodyBonusThreshold: int | None = None
    melodyBonusThresholdCoop: int | None = None
    melodyBonusThresholdNonCoop: int | None = None
    micCenterStage: bool | None = None
    micStageLeft: bool | None = None
    micStageRight: bool | None = None
    rp: int
    techFoulCount: int | None = None
    teleopAmpNoteCount: int | None = None
    teleopAmpNotePoints: int | None = None
    teleopPoints: int | None = None
    teleopSpeakerNoteAmplifiedCount: int | None = None
    teleopSpeakerNoteAmplifiedPoints: int | None = None
    teleopSpeakerNoteCount: int | None = None
    teleopSpeakerNotePoints: int | None = None
    teleopTotalNotePoints: int | None = None
    totalPoints: int
    trapCenterStage: bool | None = None
    trapStageLeft: bool | None = None
    trapStageRight: bool | None = None


class MatchTimeseries2018(BaseModel):
    event_key: str | None = Field(
        None,
        description='TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.',
    )
    match_id: str | None = Field(
        None,
        description='Match ID consisting of the level, match number, and set number, eg `qm45` or `f1m1`.',
    )
    mode: str | None = Field(
        None,
        description='Current mode of play, can be `pre_match`, `auto`, `telop`, or `post_match`.',
    )
    play: int | None = None
    time_remaining: int | None = Field(
        None,
        description='Amount of time remaining in the match, only valid during `auto` and `teleop` modes.',
    )
    blue_auto_quest: int | None = Field(
        None,
        description='1 if the blue alliance is credited with the AUTO QUEST, 0 if not.',
    )
    blue_boost_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the BOOST section of the blue alliance VAULT.',
    )
    blue_boost_played: int | None = Field(
        None,
        description='Returns 1 if the blue alliance BOOST was played, or 0 if not played.',
    )
    blue_current_powerup: str | None = Field(
        None,
        description='Name of the current blue alliance POWER UP being played, or `null`.',
    )
    blue_face_the_boss: int | None = Field(
        None,
        description='1 if the blue alliance is credited with FACING THE BOSS, 0 if not.',
    )
    blue_force_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the FORCE section of the blue alliance VAULT.',
    )
    blue_force_played: int | None = Field(
        None,
        description='Returns 1 if the blue alliance FORCE was played, or 0 if not played.',
    )
    blue_levitate_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the LEVITATE section of the blue alliance VAULT.',
    )
    blue_levitate_played: int | None = Field(
        None,
        description='Returns 1 if the blue alliance LEVITATE was played, or 0 if not played.',
    )
    blue_powerup_time_remaining: str | None = Field(
        None,
        description='Number of seconds remaining in the blue alliance POWER UP time, or 0 if none is active.',
    )
    blue_scale_owned: int | None = Field(
        None, description='1 if the blue alliance owns the SCALE, 0 if not.'
    )
    blue_score: int | None = Field(
        None, description='Current score for the blue alliance.'
    )
    blue_switch_owned: int | None = Field(
        None, description='1 if the blue alliance owns their SWITCH, 0 if not.'
    )
    red_auto_quest: int | None = Field(
        None,
        description='1 if the red alliance is credited with the AUTO QUEST, 0 if not.',
    )
    red_boost_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the BOOST section of the red alliance VAULT.',
    )
    red_boost_played: int | None = Field(
        None,
        description='Returns 1 if the red alliance BOOST was played, or 0 if not played.',
    )
    red_current_powerup: str | None = Field(
        None,
        description='Name of the current red alliance POWER UP being played, or `null`.',
    )
    red_face_the_boss: int | None = Field(
        None,
        description='1 if the red alliance is credited with FACING THE BOSS, 0 if not.',
    )
    red_force_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the FORCE section of the red alliance VAULT.',
    )
    red_force_played: int | None = Field(
        None,
        description='Returns 1 if the red alliance FORCE was played, or 0 if not played.',
    )
    red_levitate_count: int | None = Field(
        None,
        description='Number of POWER CUBES in the LEVITATE section of the red alliance VAULT.',
    )
    red_levitate_played: int | None = Field(
        None,
        description='Returns 1 if the red alliance LEVITATE was played, or 0 if not played.',
    )
    red_powerup_time_remaining: str | None = Field(
        None,
        description='Number of seconds remaining in the red alliance POWER UP time, or 0 if none is active.',
    )
    red_scale_owned: int | None = Field(
        None, description='1 if the red alliance owns the SCALE, 0 if not.'
    )
    red_score: int | None = Field(
        None, description='Current score for the red alliance.'
    )
    red_switch_owned: int | None = Field(
        None, description='1 if the red alliance owns their SWITCH, 0 if not.'
    )


class MatchAlliance(BaseModel):
    score: int = Field(
        ...,
        description='Score for this alliance. Will be null or -1 for an unplayed match.',
    )
    team_keys: list[str]
    surrogate_team_keys: list[str] = Field(
        ...,
        description='TBA team keys (eg `frc254`) of any teams playing as a surrogate.',
    )
    dq_team_keys: list[str] = Field(
        ..., description='TBA team keys (eg `frc254`) of any disqualified teams.'
    )


class Type(Enum):
    youtube = 'youtube'
    cdphotothread = 'cdphotothread'
    imgur = 'imgur'
    facebook_profile = 'facebook-profile'
    youtube_channel = 'youtube-channel'
    twitter_profile = 'twitter-profile'
    github_profile = 'github-profile'
    instagram_profile = 'instagram-profile'
    periscope_profile = 'periscope-profile'
    gitlab_profile = 'gitlab-profile'
    grabcad = 'grabcad'
    instagram_image = 'instagram-image'
    external_link = 'external-link'
    avatar = 'avatar'
    onshape = 'onshape'
    cd_thread = 'cd-thread'


class Details(BaseModel):
    base64Image: str


class Details1(BaseModel):
    author_id: int
    author_name: str
    author_url: AnyUrl
    height: int | None
    html: str
    media_id: str
    provider_name: str
    provider_url: AnyUrl
    thumbnail_height: int
    thumbnail_url: AnyUrl
    thumbnail_width: int
    title: str
    type: str
    version: str
    width: int


class Details2(BaseModel):
    model_created: AwareDatetime
    model_description: str | None
    model_image: AnyUrl
    model_name: str


class Details3(BaseModel):
    image_partial: str


class Details4(BaseModel):
    thread_title: str
    image_url: str | None


class Media(BaseModel):
    type: Type = Field(..., description='String type of the media element.')
    foreign_key: str = Field(
        ..., description='The key used to identify this media on the media site.'
    )
    details: (
        dict[str, Any] | Details | Details1 | Details2 | Details3 | Details4 | None
    ) = Field(
        None, description='If required, a JSON dict of additional media information.'
    )
    preferred: bool | None = Field(
        None, description='True if the media is of high quality.'
    )
    team_keys: list[str] = Field(
        ...,
        description='List of teams that this media belongs to. Most likely length 1.',
    )
    direct_url: str | None = Field(None, description='Direct URL to the media.')
    view_url: str | None = Field(
        None,
        description='The URL that leads to the full web page for the media, if one exists.',
    )


class MobilityRobot2023(Enum):
    No = 'No'
    Yes = 'Yes'


class Entry(BaseModel):
    context: list[str] = Field(
        ...,
        description='A list of events this team achieved the notable at. This type may change over time.',
    )
    team_key: str


class Data1(BaseModel):
    entries: list[Entry]


class NotablesInsight(BaseModel):
    data: Data1
    name: str
    year: int


class Position2016(Enum):
    field_ = ''
    A_ChevalDeFrise = 'A_ChevalDeFrise'
    A_Portcullis = 'A_Portcullis'
    B_Moat = 'B_Moat'
    B_Ramparts = 'B_Ramparts'
    C_Drawbridge = 'C_Drawbridge'
    C_SallyPort = 'C_SallyPort'
    D_RockWall = 'D_RockWall'
    D_RoughTerrain = 'D_RoughTerrain'
    NotSpecified = 'NotSpecified'


class PreMatchBay2019(Enum):
    Cargo = 'Cargo'
    Panel = 'Panel'
    Unknown = 'Unknown'


class ReefRow2025(BaseModel):
    nodeA: bool
    nodeB: bool
    nodeC: bool
    nodeD: bool
    nodeE: bool
    nodeF: bool
    nodeG: bool
    nodeH: bool
    nodeI: bool
    nodeJ: bool
    nodeK: bool
    nodeL: bool


class CmpStatus(Enum):
    NotInvited = 'NotInvited'
    PreQualified = 'PreQualified'
    EventQualified = 'EventQualified'
    PoolQualified = 'PoolQualified'
    Declined = 'Declined'


class RegionalAdvancement(BaseModel):
    cmp: bool = Field(
        ..., description='Whether or not the team qualified for Championship.'
    )
    cmp_status: CmpStatus
    qualifying_event: str | None = Field(
        None, description='The event key at which the team qualified'
    )
    qualifying_award_name: str | None = Field(
        None, description='The name of the award which qualified the team'
    )
    qualifying_pool_week: int | None = Field(
        None, description="Which week number's regional pool invitation the team got"
    )


class EventPoint1(BaseModel):
    total: int = Field(..., description='Total points awarded at this event.')
    alliance_points: int = Field(
        ..., description='Points awarded for alliance selection.'
    )
    elim_points: int = Field(
        ..., description='Points awarded for elimination match performance.'
    )
    award_points: int = Field(..., description='Points awarded for event awards.')
    event_key: str = Field(..., description='TBA Event key for this event.')
    qual_points: int = Field(
        ..., description='Points awarded for qualification match performance.'
    )


class RegionalRanking(BaseModel):
    team_key: str = Field(..., description='TBA team key for the team.')
    rank: int = Field(..., description='Numerical rank of the team, 1 being top rank.')
    rookie_bonus: int | None = Field(
        None, description='Any points added to a team as a result of the rookie bonus.'
    )
    single_event_bonus: int | None = Field(
        None,
        description='Additional points awarded in lieu of a second event, based on first event performance',
    )
    point_total: int = Field(..., description='Total district points for the team.')
    event_points: list[EventPoint1] | None = Field(
        None,
        description='List of events that contributed to the point total for the team.',
    )


class RobotAuto2016WithUnknown(Enum):
    Crossed = 'Crossed'
    None_ = 'None'
    Reached = 'Reached'
    Unknown = 'Unknown'


class RobotAuto2016WithoutUnknown(Enum):
    Crossed = 'Crossed'
    Reached = 'Reached'
    None_ = 'None'


class RobotAuto2017(Enum):
    Mobility = 'Mobility'
    None_ = 'None'
    Unknown = 'Unknown'


class Team(BaseModel):
    key: str
    nickname: str


class Event1(BaseModel):
    key: str
    name: str


class SearchIndex(BaseModel):
    teams: list[Team]
    events: list[Event1]


class Stage3TargetColor2020(Enum):
    Blue = 'Blue'
    Green = 'Green'
    Red = 'Red'
    Unknown = 'Unknown'
    Yellow = 'Yellow'


class TaxiRobot2022(Enum):
    No = 'No'
    Yes = 'Yes'


class Team1(BaseModel):
    key: str = Field(
        ...,
        description='TBA team key with the format `frcXXXX` with `XXXX` representing the team number.',
    )
    team_number: int = Field(..., description='Official team number issued by FIRST.')
    nickname: str = Field(..., description='Team nickname provided by FIRST.')
    name: str = Field(..., description='Official long name registered with FIRST.')
    school_name: str | None = Field(
        ..., description='Name of team school or affilited group registered with FIRST.'
    )
    city: str | None = Field(
        ...,
        description='City of team derived from parsing the address registered with FIRST.',
    )
    state_prov: str | None = Field(
        ...,
        description='State of team derived from parsing the address registered with FIRST.',
    )
    country: str | None = Field(
        ...,
        description='Country of team derived from parsing the address registered with FIRST.',
    )
    address: str | None = Field(
        ..., description='Will be NULL, for future development.'
    )
    postal_code: str | None = Field(
        ..., description='Postal code from the team address.'
    )
    gmaps_place_id: str | None = Field(
        ..., description='Will be NULL, for future development.'
    )
    gmaps_url: str | None = Field(
        ..., description='Will be NULL, for future development.'
    )
    lat: float | None = Field(..., description='Will be NULL, for future development.')
    lng: float | None = Field(..., description='Will be NULL, for future development.')
    location_name: str | None = Field(
        ..., description='Will be NULL, for future development.'
    )
    website: str | None = Field(
        ..., description='Official website associated with the team.'
    )
    rookie_year: int | None = Field(
        ..., description='First year the team officially competed.'
    )
    motto: str | None = Field(..., description="Team's motto or tagline.")


class Ranking2(BaseModel):
    matches_played: int | None = Field(None, description='Number of matches played.')
    qual_average: float | None = Field(
        None, description='For some years, average qualification score. Can be null.'
    )
    sort_orders: list[float] | None = Field(
        None,
        description='Ordered list of values used to determine the rank. See the `sort_order_info` property for the name of each value.',
    )
    record: Record | None = None
    rank: int | None = Field(None, description='Relative rank of this team.')
    dq: int | None = Field(
        None, description='Number of matches the team was disqualified for.'
    )
    team_key: str | None = Field(None, description='TBA team key for this rank.')


class SortOrderInfoItem1(BaseModel):
    precision: int | None = Field(
        None,
        description='The number of digits of precision used for this value, eg `2` would correspond to a value of `101.11` while `0` would correspond to `101`.',
    )
    name: str | None = Field(
        None, description='The descriptive name of the value used to sort the ranking.'
    )


class Qual(BaseModel):
    num_teams: int | None = Field(None, description='Number of teams ranked.')
    ranking: Ranking2 | None = None
    sort_order_info: list[SortOrderInfoItem1] | None = Field(
        None,
        description='Ordered list of names corresponding to the elements of the `sort_orders` array.',
    )
    status: str | None = None


class Status2(Enum):
    won = 'won'
    eliminated = 'eliminated'
    playing = 'playing'


class Playoff(BaseModel):
    level: CompLevel | None = None
    current_level_record: CurrentLevelRecord | None = None
    record: Record | None = None
    status: Status2 | None = Field(
        None, description='Current competition status for the playoffs.'
    )
    playoff_average: float | None = Field(
        None,
        description='The average match score during playoffs. Year specific. May be null if not relevant for a given year.',
    )


class TeamEventStatusAllianceBackup(BaseModel):
    out: str | None = Field(
        None, description='TBA key for the team replaced by the backup.'
    )
    in_: str | None = Field(
        None, alias='in', description='TBA key for the backup team called in.'
    )


class TeamEventStatusPlayoff(BaseModel):
    level: CompLevel | None = None
    current_level_record: CurrentLevelRecord | None = None
    record: Record | None = None
    status: Status2 | None = Field(
        None, description='Current competition status for the playoffs.'
    )
    playoff_average: float | None = Field(
        None,
        description='The average match score during playoffs. Year specific. May be null if not relevant for a given year.',
    )


class Ranking3(BaseModel):
    matches_played: int | None = Field(None, description='Number of matches played.')
    qual_average: float | None = Field(
        None, description='For some years, average qualification score. Can be null.'
    )
    sort_orders: list[float] | None = Field(
        None,
        description='Ordered list of values used to determine the rank. See the `sort_order_info` property for the name of each value.',
    )
    record: Record | None = None
    rank: int | None = Field(None, description='Relative rank of this team.')
    dq: int | None = Field(
        None, description='Number of matches the team was disqualified for.'
    )
    team_key: str | None = Field(None, description='TBA team key for this rank.')


class TeamEventStatusRank(BaseModel):
    num_teams: int | None = Field(None, description='Number of teams ranked.')
    ranking: Ranking3 | None = None
    sort_order_info: list[SortOrderInfoItem1] | None = Field(
        None,
        description='Ordered list of names corresponding to the elements of the `sort_orders` array.',
    )
    status: str | None = None


class TeamRobot(BaseModel):
    year: int = Field(..., description='Year this robot competed in.')
    robot_name: str = Field(
        ..., description='Name of the robot as provided by the team.'
    )
    key: str = Field(..., description='Internal TBA identifier for this robot.')
    team_key: str = Field(..., description='TBA team key for this robot.')


class TeamSimple(BaseModel):
    key: str = Field(
        ...,
        description='TBA team key with the format `frcXXXX` with `XXXX` representing the team number.',
    )
    team_number: int = Field(..., description='Official team number issued by FIRST.')
    nickname: str = Field(..., description='Team nickname provided by FIRST.')
    name: str = Field(..., description='Official long name registered with FIRST.')
    city: str | None = Field(
        ...,
        description='City of team derived from parsing the address registered with FIRST.',
    )
    state_prov: str | None = Field(
        ...,
        description='State of team derived from parsing the address registered with FIRST.',
    )
    country: str | None = Field(
        ...,
        description='Country of team derived from parsing the address registered with FIRST.',
    )


class Touchpad2017(Enum):
    None_ = 'None'
    ReadyForTakeoff = 'ReadyForTakeoff'


class TowerFace2016(Enum):
    Both = 'Both'
    Challenged = 'Challenged'
    None_ = 'None'
    Scaled = 'Scaled'
    Unknown = 'Unknown'


class WLTRecord(BaseModel):
    losses: int = Field(..., description='Number of losses.')
    wins: int = Field(..., description='Number of wins.')
    ties: int = Field(..., description='Number of ties.')


class Type1(Enum):
    youtube = 'youtube'
    twitch = 'twitch'
    ustream = 'ustream'
    iframe = 'iframe'
    html5 = 'html5'
    rtmp = 'rtmp'
    livestream = 'livestream'
    direct_link = 'direct_link'
    mms = 'mms'
    justin = 'justin'
    stemtv = 'stemtv'
    dacast = 'dacast'


class Webcast(BaseModel):
    type: Type1 = Field(
        ...,
        description='Type of webcast, typically descriptive of the streaming provider.',
    )
    channel: str = Field(
        ...,
        description='Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe.',
    )
    date: str | None = Field(
        None,
        description='The date for the webcast in `yyyy-mm-dd` format. May be null.',
    )
    file: str | None = Field(
        None,
        description='File identification as may be required for some types. May be null.',
    )


class ZebraTeam(BaseModel):
    team_key: str = Field(
        ...,
        description='The TBA team key for the Zebra MotionWorks data.',
        examples=['frc7332'],
    )
    xs: list[float] = Field(
        ...,
        description='A list containing doubles and nulls representing a teams X position in feet at the corresponding timestamp. A null value represents no tracking data for a given timestamp.',
    )
    ys: list[float] = Field(
        ...,
        description='A list containing doubles and nulls representing a teams Y position in feet at the corresponding timestamp. A null value represents no tracking data for a given timestamp.',
    )


class APIStatus(BaseModel):
    current_season: int = Field(..., description='Year of the current FRC season.')
    max_season: int = Field(
        ..., description='Maximum FRC season year for valid queries.'
    )
    is_datafeed_down: bool = Field(
        ..., description='True if the entire FMS API provided by FIRST is down.'
    )
    down_events: list[str] = Field(
        ...,
        description='An array of strings containing event keys of any active events that are no longer updating.',
    )
    ios: APIStatusAppVersion
    android: APIStatusAppVersion
    max_team_page: int = Field(
        ..., description='Maximum team page number for valid queries.'
    )


class Award(BaseModel):
    name: str = Field(
        ...,
        description='The name of the award as provided by FIRST. May vary for the same award type.',
    )
    award_type: int = Field(
        ...,
        description='Type of award given. See https://github.com/the-blue-alliance/the-blue-alliance/blob/main/src/backend/common/consts/award_type.py#L8',
    )
    event_key: str = Field(
        ..., description='The event_key of the event the award was won at.'
    )
    recipient_list: list[AwardRecipient] = Field(
        ...,
        description="A list of recipients of the award at the event. May have either a team_key or an awardee, both, or neither (in the case the award wasn't awarded at the event).",
    )
    year: int = Field(..., description='The year this award was won.')


class TeamData(BaseModel):
    district_seasons: int
    total_district_points: int
    total_pre_dcmp_district_points: int
    district_event_wins: int
    dcmp_wins: int
    team_awards: int
    individual_awards: int
    quals_record: WLTRecord
    elims_record: WLTRecord
    in_district_extra_play_count: int
    total_matches_played: int
    dcmp_appearances: int
    cmp_appearances: int


class DistrictInsight(BaseModel):
    district_data: DistrictData
    team_data: dict[str, TeamData] | None


class Event(BaseModel):
    key: str = Field(
        ...,
        description='TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.',
    )
    name: str = Field(
        ...,
        description='Official name of event on record either provided by FIRST or organizers of offseason event.',
    )
    event_code: str = Field(..., description='Event short code, as provided by FIRST.')
    event_type: int = Field(
        ...,
        description='Event Type, as defined here: https://github.com/the-blue-alliance/the-blue-alliance/blob/main/src/backend/common/consts/event_type.py#L8',
    )
    district: District | None
    city: str | None = Field(
        ..., description='City, town, village, etc. the event is located in.'
    )
    state_prov: str | None = Field(
        ..., description='State or Province the event is located in.'
    )
    country: str | None = Field(..., description='Country the event is located in.')
    start_date: date = Field(
        ..., description='Event start date in `yyyy-mm-dd` format.'
    )
    end_date: date = Field(..., description='Event end date in `yyyy-mm-dd` format.')
    year: int = Field(..., description='Year the event data is for.')
    short_name: str | None = Field(
        ...,
        description="Same as `name` but doesn't include event specifiers, such as 'Regional' or 'District'. May be null.",
    )
    event_type_string: str = Field(
        ..., description='Event Type, eg Regional, District, or Offseason.'
    )
    week: int | None = Field(
        ...,
        description="Week of the event relative to the first official season event, zero-indexed. Only valid for Regionals, Districts, and District Championships. Null otherwise. (Eg. A season with a week 0 'preseason' event does not count, and week 1 events will show 0 here. Seasons with a week 0.5 regional event will show week 0 for those event(s) and week 1 for week 1 events and so on.)",
    )
    address: str | None = Field(
        ..., description="Address of the event's venue, if available."
    )
    postal_code: str | None = Field(
        ..., description='Postal code from the event address.'
    )
    gmaps_place_id: str | None = Field(
        ...,
        description='Google Maps Place ID for the event address. Will be NULL, for future development.',
    )
    gmaps_url: str | None = Field(
        ...,
        description='Link to address location on Google Maps. Will be NULL, for future development.',
    )
    lat: float | None = Field(
        ...,
        description='Latitude for the event address. Will be NULL, for future development.',
    )
    lng: float | None = Field(
        ...,
        description='Longitude for the event address. Will be NULL, for future development.',
    )
    location_name: str | None = Field(
        ...,
        description='Name of the location at the address for the event, eg. Blue Alliance High School.',
    )
    timezone: str | None = Field(..., description='IANA Timezone identifier.')
    website: str | None = Field(..., description="The event's website, if any.")
    first_event_id: str | None = Field(
        ...,
        description='The FIRST internal Event ID, used to link to the event on the FRC webpage.',
    )
    first_event_code: str | None = Field(
        ...,
        description='Public facing event code used by FIRST (on frc-events.firstinspires.org, for example)',
    )
    webcasts: list[Webcast]
    division_keys: list[str] = Field(
        ..., description='An array of event keys for the divisions at this event.'
    )
    parent_event_key: str | None = Field(
        ...,
        description="The TBA Event key that represents the event's parent. Used to link back to the event from a division event. It is also the inverse relation of `divison_keys`.",
    )
    playoff_type: int | None = Field(
        ...,
        description='Playoff Type, as defined under `PlayoffType`: https://github.com/the-blue-alliance/the-blue-alliance/blob/main/src/backend/common/consts/playoff_type.py#L37, or null.',
    )
    playoff_type_string: str | None = Field(
        ..., description='String representation of the `playoff_type`, or null.'
    )
    remap_teams: dict[str, Any] | None = Field(
        ...,
        description='Map of temporary "off-season demo" team numbers to pre-rookie and B teams. Both keys and values are team keys in the format \'frc####\'. Key is the old team key (\'frc\' + numeric only), value is the new team key (\'frc\' + numeric + may include a letter suffix).',
    )


class History(BaseModel):
    events: list[Event]
    awards: list[Award]


class Alliances(BaseModel):
    red: MatchAlliance
    blue: MatchAlliance

    def sides(self) -> Iterator[MatchAlliance]:
        yield self.red
        yield self.blue


class MatchScoreBreakdown2015(BaseModel):
    blue: MatchScoreBreakdown2015Alliance
    red: MatchScoreBreakdown2015Alliance
    coopertition: Coopertition
    coopertition_points: int


class MatchScoreBreakdown2016Alliance(BaseModel):
    autoPoints: int
    teleopPoints: int | None = None
    breachPoints: int
    foulPoints: int
    capturePoints: int
    adjustPoints: int | None = None
    totalPoints: int
    tba_rpEarned: int | None
    robot1Auto: RobotAuto2016WithUnknown | None = None
    robot2Auto: RobotAuto2016WithoutUnknown | None = None
    robot3Auto: RobotAuto2016WithUnknown | None = None
    autoReachPoints: int
    autoCrossingPoints: int
    autoBouldersLow: int | None = None
    autoBouldersHigh: int | None = None
    autoBoulderPoints: int
    teleopCrossingPoints: int
    teleopBouldersLow: int
    teleopBouldersHigh: int
    teleopBoulderPoints: int
    teleopDefensesBreached: bool
    teleopChallengePoints: int
    teleopScalePoints: int
    teleopTowerCaptured: bool
    towerFaceA: TowerFace2016 | None = None
    towerFaceB: TowerFace2016 | None = None
    towerFaceC: TowerFace2016 | None = None
    towerEndStrength: int | None = None
    techFoulCount: int | None = None
    foulCount: int | None = None
    position2: Position2016
    position3: Position2016
    position4: Position2016
    position5: Position2016
    position1crossings: int
    position2crossings: int
    position3crossings: int
    position4crossings: int
    position5crossings: int


class MatchScoreBreakdown2017Alliance(BaseModel):
    autoPoints: int
    teleopPoints: int
    foulPoints: int
    adjustPoints: int | None = None
    totalPoints: int
    robot1Auto: RobotAuto2017 | None = None
    robot2Auto: RobotAuto2017 | None = None
    robot3Auto: RobotAuto2017 | None = None
    rotor1Auto: bool
    rotor2Auto: bool
    autoFuelLow: int
    autoFuelHigh: int
    autoMobilityPoints: int
    autoRotorPoints: int
    autoFuelPoints: int
    teleopFuelPoints: int
    teleopFuelLow: int
    teleopFuelHigh: int
    teleopRotorPoints: int
    kPaRankingPointAchieved: bool
    teleopTakeoffPoints: int
    kPaBonusPoints: int
    rotorBonusPoints: int
    rotor1Engaged: bool
    rotor2Engaged: bool
    rotor3Engaged: bool
    rotor4Engaged: bool
    rotorRankingPointAchieved: bool
    tba_rpEarned: int | None = None
    techFoulCount: int | None = None
    foulCount: int | None = None
    touchpadNear: Touchpad2017 | None = None
    touchpadMiddle: Touchpad2017 | None = None
    touchpadFar: Touchpad2017 | None = None


class MatchScoreBreakdown2018(BaseModel):
    blue: MatchScoreBreakdown2018Alliance
    red: MatchScoreBreakdown2018Alliance


class MatchScoreBreakdown2019Alliance(BaseModel):
    adjustPoints: int | None = None
    autoPoints: int | None = None
    bay1: Bay2019
    bay2: Bay2019
    bay3: Bay2019
    bay4: Bay2019
    bay5: Bay2019
    bay6: Bay2019
    bay7: Bay2019
    bay8: Bay2019
    cargoPoints: int
    completeRocketRankingPoint: bool
    completedRocketFar: bool | None = None
    completedRocketNear: bool | None = None
    endgameRobot1: EndgameRobot2019
    endgameRobot2: EndgameRobot2019
    endgameRobot3: EndgameRobot2019
    foulCount: int | None = None
    foulPoints: int
    habClimbPoints: int
    habDockingRankingPoint: bool
    habLineRobot1: HabLine2019
    habLineRobot2: HabLine2019
    habLineRobot3: HabLine2019
    hatchPanelPoints: int
    lowLeftRocketFar: Bay2019
    lowLeftRocketNear: Bay2019
    lowRightRocketFar: Bay2019
    lowRightRocketNear: Bay2019
    midLeftRocketFar: Bay2019
    midLeftRocketNear: Bay2019
    midRightRocketFar: Bay2019
    midRightRocketNear: Bay2019
    preMatchBay1: PreMatchBay2019
    preMatchBay2: PreMatchBay2019
    preMatchBay3: PreMatchBay2019
    preMatchBay6: PreMatchBay2019
    preMatchBay7: PreMatchBay2019
    preMatchBay8: PreMatchBay2019
    preMatchLevelRobot1: EndgameRobot2019
    preMatchLevelRobot2: EndgameRobot2019
    preMatchLevelRobot3: EndgameRobot2019
    rp: int
    sandStormBonusPoints: int
    techFoulCount: int | None = None
    teleopPoints: int
    topLeftRocketFar: Bay2019
    topLeftRocketNear: Bay2019
    topRightRocketFar: Bay2019
    topRightRocketNear: Bay2019
    totalPoints: int


class MatchScoreBreakdown2020Alliance(BaseModel):
    initLineRobot1: InitLineRobot2020
    endgameRobot1: EndgameRobot2020
    initLineRobot2: InitLineRobot2020
    endgameRobot2: EndgameRobot2020
    initLineRobot3: InitLineRobot2020
    endgameRobot3: EndgameRobot2020
    autoCellsBottom: int
    autoCellsOuter: int
    autoCellsInner: int
    teleopCellsBottom: int
    teleopCellsOuter: int
    teleopCellsInner: int
    stage1Activated: bool
    stage2Activated: bool
    stage3Activated: bool
    stage3TargetColor: Stage3TargetColor2020
    endgameRungIsLevel: EndgameRungIsLevel2020
    autoInitLinePoints: int
    autoCellPoints: int
    autoPoints: int
    teleopCellPoints: int
    controlPanelPoints: int
    endgamePoints: int
    teleopPoints: int
    shieldOperationalRankingPoint: bool
    shieldEnergizedRankingPoint: bool
    tba_shieldEnergizedRankingPointFromFoul: bool | None = Field(
        None,
        description='Unofficial TBA-computed value that indicates whether the shieldEnergizedRankingPoint was earned normally or awarded due to a foul.',
    )
    tba_numRobotsHanging: int | None = Field(
        None,
        description='Unofficial TBA-computed value that counts the number of robots who were hanging at the end of the match.',
    )
    foulCount: int
    techFoulCount: int
    adjustPoints: int | None = None
    foulPoints: int
    rp: int | None = None
    totalPoints: int


class MatchScoreBreakdown2022Alliance(BaseModel):
    taxiRobot1: TaxiRobot2022 | None = None
    endgameRobot1: EndgameRobot2022 | None = None
    taxiRobot2: TaxiRobot2022 | None = None
    endgameRobot2: EndgameRobot2022 | None = None
    taxiRobot3: TaxiRobot2022 | None = None
    endgameRobot3: EndgameRobot2022 | None = None
    autoCargoLowerNear: int | None = None
    autoCargoLowerFar: int | None = None
    autoCargoLowerBlue: int | None = None
    autoCargoLowerRed: int | None = None
    autoCargoUpperNear: int | None = None
    autoCargoUpperFar: int | None = None
    autoCargoUpperBlue: int | None = None
    autoCargoUpperRed: int | None = None
    autoCargoTotal: int | None = None
    teleopCargoLowerNear: int | None = None
    teleopCargoLowerFar: int | None = None
    teleopCargoLowerBlue: int | None = None
    teleopCargoLowerRed: int | None = None
    teleopCargoUpperNear: int | None = None
    teleopCargoUpperFar: int | None = None
    teleopCargoUpperBlue: int | None = None
    teleopCargoUpperRed: int | None = None
    teleopCargoTotal: int | None = None
    matchCargoTotal: int | None = None
    autoTaxiPoints: int | None = None
    autoCargoPoints: int | None = None
    autoPoints: int | None = None
    quintetAchieved: bool | None = None
    teleopCargoPoints: int | None = None
    endgamePoints: int | None = None
    teleopPoints: int | None = None
    cargoBonusRankingPoint: bool | None = None
    hangarBonusRankingPoint: bool | None = None
    foulCount: int | None = None
    techFoulCount: int | None = None
    adjustPoints: int | None = None
    foulPoints: int | None = None
    rp: int | None = None
    totalPoints: int | None = None


class MatchScoreBreakdown2023Alliance(BaseModel):
    activationBonusAchieved: bool | None = None
    adjustPoints: int | None = None
    autoBridgeState: BridgeState2023 | None = None
    autoChargeStationPoints: int | None = None
    autoChargeStationRobot1: AutoChargeStationRobot2023 | None = None
    autoChargeStationRobot2: AutoChargeStationRobot2023 | None = None
    autoChargeStationRobot3: AutoChargeStationRobot2023 | None = None
    autoDocked: bool | None = None
    autoCommunity: AutoCommunity | None = None
    autoGamePieceCount: int | None = None
    autoGamePiecePoints: int | None = None
    autoMobilityPoints: int
    mobilityRobot1: MobilityRobot2023
    mobilityRobot2: MobilityRobot2023
    mobilityRobot3: MobilityRobot2023
    autoPoints: int
    coopGamePieceCount: int | None = None
    coopertitionCriteriaMet: bool | None = None
    endGameBridgeState: BridgeState2023 | None = None
    endGameChargeStationPoints: int | None = None
    endGameChargeStationRobot1: EndGameChargeStationRobot2023 | None = None
    endGameChargeStationRobot2: EndGameChargeStationRobot2023 | None = None
    endGameChargeStationRobot3: EndGameChargeStationRobot2023 | None = None
    endGameParkPoints: int | None = None
    extraGamePieceCount: int | None = None
    foulCount: int
    foulPoints: int
    techFoulCount: int
    linkPoints: int | None = None
    links: list[Link] | None = None
    sustainabilityBonusAchieved: bool | None = None
    teleopCommunity: TeleopCommunity | None = None
    teleopGamePieceCount: int | None = None
    teleopGamePiecePoints: int | None = None
    totalChargeStationPoints: int | None = None
    teleopPoints: int
    rp: int
    totalPoints: int


class MatchScoreBreakdown2024(BaseModel):
    blue: MatchScoreBreakdown2024Alliance
    red: MatchScoreBreakdown2024Alliance


class AutoReef(BaseModel):
    topRow: ReefRow2025
    midRow: ReefRow2025
    botRow: ReefRow2025
    trough: int
    tba_botRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the botRow object.',
    )
    tba_midRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the midRow object.',
    )
    tba_topRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the topRow object.',
    )


class TeleopReef(BaseModel):
    topRow: ReefRow2025
    midRow: ReefRow2025
    botRow: ReefRow2025
    trough: int
    tba_botRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the botRow object.',
    )
    tba_midRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the midRow object.',
    )
    tba_topRowCount: int | None = Field(
        None,
        description='Unofficial TBA-computed value that sums the total number of game pieces scored in the topRow object.',
    )


class MatchScoreBreakdown2025Alliance(BaseModel):
    adjustPoints: int | None = None
    algaePoints: int
    autoBonusAchieved: bool | None = None
    autoCoralCount: int
    autoCoralPoints: int
    autoLineRobot1: AutoLineRobot2024
    autoLineRobot2: AutoLineRobot2024
    autoLineRobot3: AutoLineRobot2024
    autoMobilityPoints: int
    autoPoints: int
    autoReef: AutoReef
    bargeBonusAchieved: bool | None = None
    coopertitionCriteriaMet: bool | None = None
    coralBonusAchieved: bool | None = None
    endGameBargePoints: int
    endGameRobot1: EndGameRobot2025
    endGameRobot2: EndGameRobot2025
    endGameRobot3: EndGameRobot2025
    foulCount: int
    foulPoints: int
    g206Penalty: bool
    g410Penalty: bool
    g418Penalty: bool
    g428Penalty: bool
    netAlgaeCount: int
    rp: int
    techFoulCount: int
    teleopCoralCount: int
    teleopCoralPoints: int
    teleopPoints: int
    teleopReef: TeleopReef
    totalPoints: int
    wallAlgaeCount: int


class MatchSimple(BaseModel):
    key: str = Field(
        ...,
        description='TBA match key with the format `yyyy[EVENT_CODE]_[COMP_LEVEL]m[MATCH_NUMBER]`, where `yyyy` is the year, and `EVENT_CODE` is the event code of the event, `COMP_LEVEL` is (qm, ef, qf, sf, f), and `MATCH_NUMBER` is the match number in the competition level. A set number may append the competition level if more than one match in required per set.',
    )
    comp_level: CompLevel
    set_number: int = Field(
        ...,
        description='The set number in a series of matches where more than one match is required in the match series.',
    )
    match_number: int = Field(
        ..., description='The match number of the match in the competition level.'
    )
    alliances: Alliances = Field(
        ...,
        description='A list of alliances, the teams on the alliances, and their score.',
    )
    winning_alliance: WinningAlliance = Field(
        ...,
        description='The color (red/blue) of the winning alliance. Will contain an empty string in the event of no winner, or a tie.',
    )
    event_key: str = Field(
        ..., description='Event key of the event the match was played at.'
    )
    time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the scheduled match time, as taken from the published schedule.',
    )
    predicted_time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the TBA predicted match start time.',
    )
    actual_time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of actual match start time.',
    )


class Alliance(BaseModel):
    name: str | None = Field(None, description='Alliance name, may be null.')
    number: int = Field(..., description='Alliance number.')
    backup: TeamEventStatusAllianceBackup | None = None
    pick: int = Field(
        ...,
        description='Order the team was picked in the alliance from 0-2, with 0 being alliance captain.',
    )


class TeamEventStatus(BaseModel):
    qual: Qual | None = None
    alliance: Alliance | None = None
    playoff: Playoff | None = None
    alliance_status_str: str | None = Field(
        None,
        description="An HTML formatted string suitable for display to the user containing the team's alliance pick status.",
    )
    playoff_status_str: str | None = Field(
        None,
        description="An HTML formatter string suitable for display to the user containing the team's playoff status.",
    )
    overall_status_str: str | None = Field(
        None,
        description="An HTML formatted string suitable for display to the user containing the team's overall status summary of the event.",
    )
    next_match_key: str | None = Field(
        None,
        description='TBA match key for the next match the team is scheduled to play in at this event, or null.',
    )
    last_match_key: str | None = Field(
        None,
        description='TBA match key for the last match the team played in at this event, or null.',
    )


class TeamEventStatusAlliance(BaseModel):
    name: str | None = Field(None, description='Alliance name, may be null.')
    number: int = Field(..., description='Alliance number.')
    backup: TeamEventStatusAllianceBackup | None = None
    pick: int = Field(
        ...,
        description='Order the team was picked in the alliance from 0-2, with 0 being alliance captain.',
    )


class Alliances2(BaseModel):
    red: list[ZebraTeam] | None = Field(
        None, description='Zebra MotionWorks data for teams on the red alliance'
    )
    blue: list[ZebraTeam] | None = Field(
        None, description='Zebra data for teams on the blue alliance'
    )


class Zebra(BaseModel):
    key: str = Field(
        ...,
        description='TBA match key with the format `yyyy[EVENT_CODE]_[COMP_LEVEL]m[MATCH_NUMBER]`, where `yyyy` is the year, and `EVENT_CODE` is the event code of the event, `COMP_LEVEL` is (qm, ef, qf, sf, f), and `MATCH_NUMBER` is the match number in the competition level. A set number may be appended to the competition level if more than one match in required per set.',
    )
    times: list[float] = Field(
        ...,
        description='A list of relative timestamps for each data point. Each timestamp will correspond to the X and Y value at the same index in a team xs and ys arrays. `times`, all teams `xs` and all teams `ys` are guarenteed to be the same length.',
    )
    alliances: Alliances2


class MatchScoreBreakdown2016(BaseModel):
    blue: MatchScoreBreakdown2016Alliance
    red: MatchScoreBreakdown2016Alliance


class MatchScoreBreakdown2017(BaseModel):
    blue: MatchScoreBreakdown2017Alliance
    red: MatchScoreBreakdown2017Alliance


class MatchScoreBreakdown2019(BaseModel):
    blue: MatchScoreBreakdown2019Alliance
    red: MatchScoreBreakdown2019Alliance


class MatchScoreBreakdown2020(BaseModel):
    blue: MatchScoreBreakdown2020Alliance
    red: MatchScoreBreakdown2020Alliance


class MatchScoreBreakdown2022(BaseModel):
    blue: MatchScoreBreakdown2022Alliance
    red: MatchScoreBreakdown2022Alliance


class MatchScoreBreakdown2023(BaseModel):
    blue: MatchScoreBreakdown2023Alliance
    red: MatchScoreBreakdown2023Alliance


class MatchScoreBreakdown2025(BaseModel):
    blue: MatchScoreBreakdown2025Alliance
    red: MatchScoreBreakdown2025Alliance


class Match(BaseModel):
    key: str = Field(
        ...,
        description='TBA match key with the format `yyyy[EVENT_CODE]_[COMP_LEVEL]m[MATCH_NUMBER]`, where `yyyy` is the year, and `EVENT_CODE` is the event code of the event, `COMP_LEVEL` is (qm, ef, qf, sf, f), and `MATCH_NUMBER` is the match number in the competition level. A set number may be appended to the competition level if more than one match in required per set.',
    )
    comp_level: CompLevel
    set_number: int = Field(
        ...,
        description='The set number in a series of matches where more than one match is required in the match series.',
    )
    match_number: int = Field(
        ..., description='The match number of the match in the competition level.'
    )
    alliances: Alliances = Field(
        ...,
        description='A list of alliances, the teams on the alliances, and their score.',
    )
    winning_alliance: WinningAlliance = Field(
        ...,
        description='The color (red/blue) of the winning alliance. Will contain an empty string in the event of no winner, or a tie.',
    )
    event_key: str = Field(
        ..., description='Event key of the event the match was played at.'
    )
    time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the scheduled match time, as taken from the published schedule.',
    )
    actual_time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of actual match start time.',
    )
    predicted_time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) of the TBA predicted match start time.',
    )
    post_result_time: int | None = Field(
        ...,
        description='UNIX timestamp (seconds since 1-Jan-1970 00:00:00) when the match result was posted.',
    )
    score_breakdown: (
        MatchScoreBreakdown2015
        | MatchScoreBreakdown2016
        | MatchScoreBreakdown2017
        | MatchScoreBreakdown2018
        | MatchScoreBreakdown2019
        | MatchScoreBreakdown2020
        | MatchScoreBreakdown2022
        | MatchScoreBreakdown2023
        | MatchScoreBreakdown2024
        | MatchScoreBreakdown2025
        | None
    ) = Field(
        ...,
        description='Score breakdown for auto, teleop, etc. points. Varies from year to year. May be null.',
    )
    videos: list[Video] = Field(
        ..., description='Array of video objects associated with this match.'
    )
